#.streamlit/secrets.toml

[connections.snowflake]
account = "OVHEUYN-EJB27295"
user = "diyat"
password = "WednesdayAddams0#"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
